apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disk-prome"
  namespace: "openshift-local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mon00.ocp-core-jkt.pegadaian.co.id
          - mon01.ocp-core-jkt.pegadaian.co.id
  storageClassDevices:
    - storageClassName: "local-disk-prome"
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
      - /dev/sdb
